### ISSUE TITLE
can't generate from env.json

### ISSUE THREAD

**Issue by ayyuby26** [nsNeruno/flutter_dd_cli#1]
I installed the package with 
> flutter pub global activate flutter_dd_cli

log:
> ayub@192 ~ % flutter pub global activate flutter_dd_cli
Resolving dependencies...
> + flutter_dd_cli 0.2.0
> + meta 1.8.0
Downloading flutter_dd_cli 0.2.0...
Downloading meta 1.8.0...
Installed executable fdd.
Warning: Executable "fdd" runs "bin/fdd.dart", which was not found in flutter_dd_cli.
Activated flutter_dd_cli 0.2.0.

 
if I don't run the command below I get an error

> dart pub global activate flutter_dd_cli

error: 
> No active package flutter_dd_cli.

and I have installed pub-cache to env (macOs)
> export PATH="$PATH":"$HOME/flutter/.pub-cache/bin"

is there something wrong with the installation steps? here is the error code

> ayub@192 project % fdd generate assets/config/dev.json
Unhandled exception:
'null': Switch case fall-through at line 0.
#0      FlutterDDCLI._getFileType (package:flutter_dd_cli/flutter_dd_cli.dart:44:5)
#1      FlutterDDCLI.run (package:flutter_dd_cli/flutter_dd_cli.dart:165:39)
#2      main (file:///Users/ayub/.pub-cache/hosted/pub.dartlang.org/flutter_dd_cli-0.2.0/bin/fdd.dart:5:13)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by nsNeruno** [comment]
Please add the missing parameter `json`
**Example:**
`fdd generate json assets/config/dev.json`

Will add proper error messaging on future updates

**Comment by ayyuby26** [comment]
less json parameter
